### ISSUE TITLE
plone code analysis fails

### ISSUE THREAD

**Issue by jensens** [collective/cookiecutter-plone-starter#15]
I get 
```
There was an error, see /home/jensens/ws/cdev/plone-training-test/plone_starter_error.log for details
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
~/ws/cdev/plone-training-test$ 
~/ws/cdev/plone-training-test$ cat plone_starter_error.log 
+ dirname /home/jensens/ws/cdev/plone-training-test/plone-comf/backend/Makefile
++ tput setaf 2
++ tput sgr0
+ echo '==> Format codebase'
+++ whoami
++ id -u jensens
++ cut -d: -f3
+++ whoami
++ getent group jensens
+ docker run --rm --user=1000:1000 -e LOG_LEVEL=INFO -v /home/jensens/ws/cdev/plone-training-test/plone-comf/backend:/github/workspace plone/code-quality:2.0.0 format

============================
Starting plone-code-analysis
============================

Running formatter: black
========================
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 70, in <module>
    status = ACTIONS[action](settings, tool, paths)
  File "/usr/local/lib/python3.10/site-packages/plone_code_analysis/format.py", line 58, in run_formatters
    status = run_formatter(formatter, paths) or status
  File "/usr/local/lib/python3.10/site-packages/plone_code_analysis/format.py", line 43, in run_formatter
    return func(*args, paths=paths)
  File "/usr/local/lib/python3.10/site-packages/plone_code_analysis/cmd.py", line 25, in run_command
    all_args = cmd + args + paths
TypeError: can only concatenate list (not "str") to list
make: *** [Makefile:102: format] Error 1
```

Maybe easier to solve this with #5

**Comment by jensens** [comment]
it happens I had set a docker context to a server which then fails running this
