### ISSUE TITLE
cannot update Browserlist with instruction from the warning

### ISSUE THREAD

**Issue by fredvd** [collective/cookiecutter-plone-starter#150]
Whenever I start my project that was created with cookiecutter-plone-starter, I see the following warning:

```
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
```

When I execute `npx update-browserslist-db@latest` I run into issues.  the command wants to install browserslist using npm, then it tries to install caniuse-lite with npm and that fails with dependency issues and other errors I frankly don't understand. 

```
 npx update-browserslist-db@latest
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Latest version:     1.0.30001668
Installed version:  none
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ npm install caniuse-lite
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: frontend@1.0.0
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"18.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.3.0" from react-intl@3.12.1
npm error node_modules/react-intl
npm error   react-intl@"3.12.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/fred/.npm/_logs/2024-10-11T10_40_00_008Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/fred/.npm/_logs/2024-10-11T10_40_00_008Z-debug-0.log

Error: Command failed: npm install caniuse-lite
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: frontend@1.0.0
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"18.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.3.0" from react-intl@3.12.1
npm error node_modules/react-intl
npm error   react-intl@"3.12.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/fred/.npm/_logs/2024-10-11T10_40_00_008Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/fred/.npm/_logs/2024-10-11T10_40_00_008Z-debug-0.log

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at updatePackageManually (/Users/fred/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/index.js:233:5)
    at updateDB (/Users/fred/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/index.js:301:5)
    at Object.<anonymous> (/Users/fred/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/cli.js:34:5)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)

Problem with `npm install caniuse-lite` call. Run it manually.
```

Also, after running this the package-lock.json was changed, where caniuse-lite is removed from it: 

```
       }
     },
-    "node_modules/caniuse-lite": {
-      "version": "1.0.30001588",
-      "funding": [
-        {
-          "type": "opencollective",
-          "url": "https://opencollective.com/browserslist"
-        },
-        {
-          "type": "tidelift",
-          "url": "https://tidelift.com/funding/github/npm/caniuse-lite"
-        },
-        {
-          "type": "github",
-          "url": "https://github.com/sponsors/ai"
-        }
-      ],
-      "license": "CC-BY-4.0"
-    },
     "node_modules/capture-exit": {
       "version": "2.0.0",
       "license": "ISC",
@@ -50782,9 +50764,6 @@
         "lodash.uniq": "^4.5.0"
       }
     },
-    "caniuse-lite": {
-      "version": "1.0.30001588"
-    },
```

**Comment by fredvd** [comment]
Solved. There was a spurrious package-lock.json in the project root next to the yarn.lock.  browserslist probably checks for that and decided to use npm to install caniuse-lite. Which then fails.  Remove package-lock.json and yarn is used to updat caniuse-lite.
