### ISSUE TITLE
UnicodeEncodeError installing Plone 6

### ISSUE THREAD

**Issue by abarbaracb** [collective/cookiecutter-plone-starter#32]
```
================================================================================
Project Title generation
================================================================================
Running sanity checks
Traceback (most recent call last):
  File "/tmp/tmpe3frarf1.py", line 259, in <module>
    main()
  File "/tmp/tmpe3frarf1.py", line 235, in main
    if not sanity_check():
  File "/tmp/tmpe3frarf1.py", line 213, in sanity_check
    print(f"  - {title}: {msg}")
  File "/usr/lib/python3.8/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 19: character maps to <undefined>
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

**Comment by jensens** [comment]
additional information https://community.plone.org/t/error-installing-plone-6-with-cookiecutter/15764/3

**Comment by jensens** [comment]
Seem to be the locale (see additional information above) 

OTHO it should work with other locale settings as well or at least we need a quick check if the locale is right and return a more verbose error with a good hint what to do.
