### ISSUE TITLE
hyphen or underscore breaking `make install`

### ISSUE THREAD

**Issue by flipmcf** [collective/cookiecutter-plone-starter#49]
I have some evidence that either a hyphen or underscore is breaking 'make install' somewhere.  Unfortunately I have little data than what I got.  Removing the '-' from project slug AND removing '_' from 'python package name' made the error go away.

Not sure which field causes it yet.

```
python3 -m cookiecutter gh:collective/cookiecutter-plone-starter
You've downloaded /home/flipmcf/.cookiecutters/cookiecutter-plone-starter before. Is it okay to delete and re-download it? [yes]: yes
project_title [Project Title]: RFA QSL
project_slug [rfa-qsl]: 
description [A new project using Plone 6.]: RFA QSL Website
author [Plone Foundation]: Michael McFadden - Radio Free Asia
email [collective@plone.org]:
python_package_name [rfa_qsl]: 
plone_version [6.0.0rc2]: 
volto_version [16.3.0]: 
volto_generator_version [6.0.0-alpha.4]: 
Select language_code:
1 - en
2 - de
3 - es
4 - pt-br
Choose from 1, 2, 3, 4 [1]: 
github_organization [collective]: RadioFreeAsia
Select container_registry:
1 - Docker Hub
2 - GitHub
Choose from 1, 2 [1]: 
================================================================================
RFA QSL generation
================================================================================
Running sanity checks
  - Python: ✓
  - Node: ✓
  - yo: ✓
  - Docker: ✓
  - git: ✓

Summary:
  - Plone version: 6.0.0rc2
  - Volto version: 16.3.0
  - Volto Generator version: 6.0.0-alpha.4
  - Output folder: /home/flipmcf/repos/rfa-qsl

Frontend codebase:
 - Installing @plone/generator-volto@6.0.0-alpha.4
 - Generate frontend application with @plone/volto 16.3.0

Backend codebase
 - Format generated code in the backend
```

make install

```
Could not import rfa-qsl. Set environment variable AUTOINCLUDE_ALLOW_MODULE_NOT_FOUND_ERROR=1 if you want to allow this. Or set it to 'rfa-qsl' to only allow for this project. Can be a comma-separated list of project names. Or replace the z3c.autoinclude.plugin entry point of this project with plone.autoinclude.plugin and a module name.
Traceback (most recent call last):
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self.context.end()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/config.py", line 873, in finish
    actions = self.handler(context, **args)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/plone/autoinclude/zcml.py", line 37, in includePluginsDirective
    dists = loader.load_packages(target)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/plone/autoinclude/loader.py", line 145, in load_packages
    z3c_dists = load_z3c_packages(target=target)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/plone/autoinclude/loader.py", line 56, in load_z3c_packages
    dist = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rfa-qsl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/zconsole", line 8, in <module>
    sys.exit(main())
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/utilities/zconsole.py", line 50, in main
    runscript(namespace.zopeconf, *namespace.scriptargs)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/utilities/zconsole.py", line 13, in runscript
    make_wsgi_app({}, zopeconf)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/Startup/run.py", line 61, in make_wsgi_app
    starter.prepare()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/Startup/starter.py", line 38, in prepare
    self.startZope()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/Startup/starter.py", line 94, in startZope
    Zope2.startup_wsgi()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/__init__.py", line 36, in startup_wsgi
    _startup()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/App/startup.py", line 126, in startup
    load_zcml()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/App/startup.py", line 41, in load_zcml
    load_site()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 663, in file
    include(context, name, package)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 560, in include
    processxmlfile(f, context)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 409, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 395, in endElementNS
    self._handle_exception(ex, info)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self.context.end()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/config.py", line 873, in finish
    actions = self.handler(context, **args)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/OFS/metaconfigure.py", line 47, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 560, in include
    processxmlfile(f, context)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 409, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 395, in endElementNS
    self._handle_exception(ex, info)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 237, in _handle_exception
    reraise(exc, None, sys.exc_info()[2])
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/_compat.py", line 31, in reraise
    raise value.with_traceback(tb)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self.context.end()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/zope/configuration/config.py", line 873, in finish
    actions = self.handler(context, **args)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/plone/autoinclude/zcml.py", line 37, in includePluginsDirective
    dists = loader.load_packages(target)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/plone/autoinclude/loader.py", line 145, in load_packages
    z3c_dists = load_z3c_packages(target=target)
  File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/plone/autoinclude/loader.py", line 56, in load_z3c_packages
    dist = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/flipmcf/repos/rfa-qsl/backend/lib/python3.8/site-packages/Products/CMFPlone/meta.zcml", line 38.4-42.10
    File "/home/flipmcf/repos/rfa-qsl/backend/instance/etc/site.zcml", line 13.2-13.39
    ModuleNotFoundError: No module named 'rfa-qsl'
make[3]: *** [Makefile:154: create-site] Error 1
make[2]: *** [Makefile:53: create-site] Error 2
make[1]: *** [Makefile:44: install-backend] Error 2
make: *** [Makefile:61: install] Error 2
```

**Comment by davisagli** [comment]
I investigated and think this was caused by a change in plone.autoinclude: https://github.com/plone/plone.autoinclude/pull/21

**Comment by davisagli** [comment]
@flipmcf This was fixed. I just tested using latest versions of Plone and Volto, and it worked.
